name: Setup
inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.10"
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry
      run: python -m pip install poetry
      shell: bash
    - name: Configure poetry
      run: python -m poetry config virtualenvs.in-project true
      shell: bash
    - name: Cache the virtualenv
      uses: actions/cache@v2
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: poetry install --no-ansi
      shell: bash
