name: Testing

on: [push]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/actions/python-setup
      - name: Analysing the code with pylint
        run: |
          poetry run pylint $(git ls-files '*.py')
  test:
    runs-on: ubuntu-latest
    name: Run unittests
    steps:
      - uses: actions/checkout@v3
      - id: bar
        uses: ./.github/actions/python-setup
      - name: Running unittests
        run: |
          poetry run pytest
